- name: Checkout code
  uses: actions/checkout@master
- name: Update diagram
  uses: githubocto/repo-visualizer@0.7.1
  with:
    output_file: "code-diagram.svg"
    excluded_paths: "dist,node_modules"